name: CI

on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "*" ]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Discord Webhook  
        uses: enbraining/discord-webhook-action@v0.0.3-alpha
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: "test"
          # content: "# Hello World"
          type: EMBEDS
          title: HELLO