name: CI

on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "*" ]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Discord Webhook  
        uses: enbraining/discord-webhook-action@v0.0.4-alpha
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: "test"
          type: EMBEDS
          title: "hello"
          description: "world"
          image-url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc9APxkj0xClmrU3PpMZglHQkx446nQPG6lA&s"